// Package auth issues and verifies API keys, and resolves them to a tenant.
package auth

import (
	"crypto/rand"
	"crypto/sha256"
	"encoding/base64"
	"fmt"
	"strings"
)

const (
	// 256 bits of CSPRNG output. Long enough that offline brute force is not a
	// threat, which is why a password KDF is not used to store these.
	secretBytes = 32
	prefixLen   = 11
)

// Key is a freshly minted credential. Secret is returned to the caller exactly
// once and is never stored; only Hash and Prefix are persisted.
type Key struct {
	Secret string
	Prefix string
	Hash   []byte
}

// NewKey mints a token of the form tf_<env>_<base64url secret>.
func NewKey(env string) (Key, error) {
	if env != "live" && env != "test" {
		return Key{}, fmt.Errorf("key env must be live or test, got %q", env)
	}
	buf := make([]byte, secretBytes)
	if _, err := rand.Read(buf); err != nil {
		return Key{}, fmt.Errorf("generate key: %w", err)
	}
	secret := "tf_" + env + "_" + base64.RawURLEncoding.EncodeToString(buf)
	return Key{Secret: secret, Prefix: secret[:prefixLen], Hash: hash(secret)}, nil
}

// hash is the lookup value for a token. SHA-256 is appropriate precisely
// because the input is high-entropy and generated by us.
func hash(secret string) []byte {
	sum := sha256.Sum256([]byte(secret))
	return sum[:]
}

// parseToken rejects anything not shaped like one of our tokens before it
// reaches the database, so malformed input costs no query.
func parseToken(token string) ([]byte, error) {
	if !strings.HasPrefix(token, "tf_live_") && !strings.HasPrefix(token, "tf_test_") {
		return nil, ErrUnauthorized
	}
	if len(token) != len("tf_live_")+base64.RawURLEncoding.EncodedLen(secretBytes) {
		return nil, ErrUnauthorized
	}
	return hash(token), nil
}
